export type B =
  | { t: "h2" | "h3" | "p" | "notice" | "verify"; x: string }
  | { t: "ul" | "ol"; x: string[] }
  | { t: "faq"; x: [string, string][] }
  | { t: "cta"; x: [string, string][] };
export type Page = { path: string; title: string; desc: string; h1: string; parent?: string; crumb: string; schema?: "Service"; form?: "enquiry" | "profile" | "vacancies" | "list"; blocks: B[] };

const V = (x: string): B => ({ t: "verify", x: "VERIFY BEFORE PUBLISH: " + x });
const DISC = "Sea Hawk provides this page for general educational guidance. It is not the issuing authority for statutory certificates and does not guarantee eligibility, admission, examination success, document issuance or employment. Always confirm the latest requirement from DG Shipping, the relevant maritime administration or an approved institution.";
const OFFICIAL = "Verify on Official Source: DG Shipping official portal (https://www.dgshipping.gov.in/). Review this link every quarter and whenever regulations change.";
const guide = (slug: string, title: string, kw: string, intro: string, steps: string[], desc: string): Page => ({
  path: `/seafarers/guidance/${slug}/`, title: `${title} | Sea Hawk Seafarer Hub`, desc, h1: title, parent: "/seafarers/guidance/", crumb: title,
  blocks: [{ t: "h2", x: "Overview" }, { t: "p", x: intro }, { t: "h2", x: "Recommended Steps" }, { t: "ol", x: steps },
    { t: "h2", x: "Important Disclaimer" }, { t: "notice", x: DISC }, { t: "h2", x: "Official Source Block" },
    { t: "p", x: "Verify the latest requirement on the official source. Last reviewed: [INSERT REVIEW DATE]." },
    { t: "cta", x: [["https://www.dgshipping.gov.in/", "Verify on Official Source"]] }] });

export const pages: Page[] = [
{ path: "/services/", title: "Ship Management Services | Commercial, Technical, Crew & Marine", desc: "Explore Sea Hawk Ship Management services including commercial management, technical management, crew management, marine consultancy and offshore support.", h1: "Maritime Services Built Around Operational Requirements", crumb: "Services", blocks: [
 { t: "p", x: "Different vessels and owners require different levels of management support. Sea Hawk provides modular and integrated maritime services that can be scoped according to operational need, available in-house capability, contractual responsibility and applicable regulation." },
 { t: "h2", x: "Commercial Management" }, { t: "p", x: "Support for chartering coordination, marine accounting, post-fixture operations and commercial performance oversight." }, { t: "cta", x: [["/services/commercial-management/", "Commercial Management"]] },
 { t: "h2", x: "Technical Management" }, { t: "p", x: "Support for maintenance, inspection, repair coordination, condition monitoring and technical reliability." }, { t: "cta", x: [["/services/technical-management/", "Technical Management"]] },
 { t: "h2", x: "Crew Management" }, { t: "p", x: "Crew-related sourcing, administration, training/development coordination, payroll and travel logistics, subject to applicable licensing." }, { t: "cta", x: [["/services/crew-management/", "Crew Management"]] },
 { t: "h2", x: "Marine Consultancy" }, { t: "p", x: "Experienced maritime input for operational, offshore, rig and project-specific requirements." }, { t: "cta", x: [["/services/marine-consultancy/", "Marine Consultancy"]] },
 { t: "h2", x: "Offshore & Marine Support" }, { t: "p", x: "Support for offshore-vessel and marine-project requirements where Sea Hawk has the relevant competence and agreed scope." }, { t: "cta", x: [["/services/offshore-marine-support/", "Offshore & Marine Support"]] },
 { t: "h2", x: "Service Enquiry" }, { t: "p", x: "Not sure which service applies? Share your vessel type, current challenge and expected scope." }, { t: "cta", x: [["/ship-owners/enquiry/", "Request a Service Discussion"]] }] },

{ path: "/services/commercial-management/", schema: "Service", title: "Commercial Ship Management Services | Sea Hawk", desc: "Commercial ship management support including chartering coordination, post-fixture operations, marine accounting and commercial performance oversight.", h1: "Commercial Management Focused on Practical Vessel Performance", parent: "/services/", crumb: "Commercial Management", blocks: [
 { t: "p", x: "Commercial management connects market opportunity with day-to-day vessel execution. Sea Hawk provides commercial management support designed to help owners maintain clear oversight of fixtures, voyage performance, accounting and post-fixture requirements within the agreed management scope." },
 { t: "h2", x: "Scope of Support" }, { t: "ul", x: ["Chartering and fixture coordination support.", "Post-fixture operational follow-up.", "Voyage and commercial performance monitoring.", "Marine accounting and commercial reporting support.", "Communication between owner, charterer, vessel and relevant service providers.", "Support related to sales and purchase activity where specifically agreed.", "Coordination with crew and technical teams when commercial decisions affect operations."] },
 { t: "h2", x: "How We Work" }, { t: "p", x: "Before engagement, the responsibilities of Sea Hawk, the owner and any third-party manager should be clearly documented. Reporting frequency, approval limits, escalation points and data access should be agreed so that commercial decisions are traceable and timely." },
 { t: "h2", x: "Who This Service Is For" }, { t: "ul", x: ["Ship owners seeking outsourced commercial support.", "Vessel operators requiring additional shore-side commercial capacity.", "Owners requiring defined support for specific vessels or voyages.", "Maritime businesses needing coordinated commercial and operational reporting."] },
 { t: "h2", x: "Frequently Asked Questions" }, { t: "faq", x: [["Do you provide full commercial management or selected services?", "Both models can be discussed. The final scope depends on vessel type, owner requirements, available resources and contractual responsibility."], ["Do you manage all vessel types?", "Sea Hawk lists only vessel segments for which the company has verified experience. The enquiry form captures vessel type before committing to scope."], ["Can commercial management be combined with crew or technical services?", "Yes, integrated scopes can be considered where Sea Hawk has the necessary capability and regulatory authority."]] },
 { t: "h2", x: "Discuss Commercial Management" }, { t: "p", x: "Tell us the vessel type, operating profile and areas where you need support." }, { t: "cta", x: [["/ship-owners/enquiry/", "Submit Commercial Enquiry"]] }] },

{ path: "/services/technical-management/", schema: "Service", title: "Technical Ship Management Services | Sea Hawk", desc: "Technical ship management support for vessel maintenance, inspection, repair coordination, condition monitoring and operational reliability.", h1: "Technical Management for Reliable Vessel Operations", parent: "/services/", crumb: "Technical Management", blocks: [
 { t: "p", x: "Reliable vessel performance depends on planned maintenance, competent technical oversight and timely corrective action. Sea Hawk provides technical management support focused on asset condition, operational continuity and clear coordination between vessel and shore teams." },
 { t: "h2", x: "Service Scope" }, { t: "ul", x: ["Planned maintenance coordination and follow-up.", "Inspection and condition-monitoring support.", "Repair and service coordination with approved vendors.", "Testing, calibration and equipment compliance tracking where applicable.", "Technical defect follow-up and escalation.", "Spare parts and procurement coordination where included in scope.", "Dry-dock / repair-period planning support where competence and contract allow.", "Technical reporting and owner updates."] },
 { t: "h2", x: "Maintenance Philosophy" }, { t: "p", x: "The technical management approach prioritises preventive planning over reactive repair, while recognising that operating conditions, class requirements, manufacturer guidance and the vessel’s safety management system determine the actual maintenance programme." },
 { t: "h2", x: "Safety & Compliance Interface" }, { t: "p", x: "Technical activity must align with applicable flag, class, statutory and client requirements. Sea Hawk does not claim class or statutory authority unless specifically authorised to perform those functions." },
 { t: "h2", x: "Frequently Asked Questions" }, { t: "faq", x: [["Can Sea Hawk take over a vessel’s existing maintenance system?", "A transition can be assessed based on data quality, access, vessel condition and contractual scope. Any migration should begin with a documented handover and gap review."], ["Do you handle emergency defects?", "The company may provide coordination support according to the service agreement and team availability. Emergency response obligations should be defined contractually."], ["Can technical management be offered independently?", "Yes, a modular technical scope can be considered depending on vessel type and operational requirements."]] },
 { t: "h2", x: "Technical Management Enquiry" }, { t: "p", x: "Share vessel type, age, current management arrangement and the support required." }, { t: "cta", x: [["/ship-owners/enquiry/", "Talk to Technical Team"]] }] },

{ path: "/services/crew-management/", schema: "Service", title: "Crew Management Services in India | Sea Hawk", desc: "Crew management support covering sourcing, administration, deployment coordination, training support, payroll and crew travel logistics, subject to applicable regulations.", h1: "Crew Management Built Around Competence, Continuity and Care", parent: "/services/", crumb: "Crew Management", blocks: [
 { t: "p", x: "People are central to safe vessel operations. Sea Hawk provides crew management support intended to help ship owners and operators coordinate competent manpower, documentation, deployment, payroll and crew logistics in a structured manner." },
 { t: "h2", x: "Crew Management Scope" }, { t: "ul", x: ["Crew sourcing and candidate coordination subject to valid regulatory authorisation.", "Document and qualification screening against role requirements.", "Interview and selection coordination with owner/operator approval.", "Pre-joining administration and deployment coordination.", "Training and development coordination.", "Crew payroll administration where included in scope.", "Travel planning and logistics coordination.", "Crew rotation and relief planning.", "Record management and expiry tracking.", "Performance feedback and retention support."] },
 { t: "h2", x: "Responsible Recruitment" }, { t: "p", x: "Sea Hawk does not promise guaranteed placement. Candidates should not make payments to unauthorised persons or unofficial accounts. Recruitment processes follow the licence scope and applicable DG Shipping requirements." },
 V("RPSL number and verification link are not shown until the current DG Shipping status is independently verified. Do not state that Sea Hawk is authorised to recruit/place Indian seafarers before then."),
 { t: "h2", x: "For Ship Owners" }, { t: "p", x: "Owners can submit rank requirements, vessel type, joining window, flag, contract duration, experience criteria and any special competency requirement through the dedicated crew enquiry form." },
 { t: "h2", x: "For Seafarers" }, { t: "p", x: "Seafarers should use the official profile form to submit accurate, current information. Sea Hawk may request verification of certificates and sea-service records. Submission of a profile does not guarantee selection or employment." },
 { t: "h2", x: "Frequently Asked Questions" }, { t: "faq", x: [["Does profile registration guarantee a job?", "No. Registration only allows the company to assess the profile against available and future requirements."], ["Should seafarers pay an agent for placement?", "Use only official Sea Hawk channels and follow applicable recruitment rules. Report suspicious payment requests through the fraud-reporting channel."], ["Can foreign-national crew be considered?", "This depends on the client requirement, flag/immigration rules and Sea Hawk’s legal ability to source in the relevant jurisdiction."]] },
 { t: "h2", x: "Crew Management Enquiry" }, { t: "p", x: "For owners and operators requiring crew support, submit the vessel and rank requirements." }, { t: "cta", x: [["/ship-owners/enquiry/", "Request Crew Support"], ["/seafarers/profile/", "Seafarer Registration"]] }] },

{ path: "/services/marine-consultancy/", schema: "Service", title: "Marine Consultancy Services India | Sea Hawk", desc: "Practical marine consultancy for maritime, offshore, rig and project requirements, delivered by appropriately experienced professionals.", h1: "Practical Marine Consultancy for Operational Decisions", parent: "/services/", crumb: "Marine Consultancy", blocks: [
 { t: "p", x: "Marine projects often require experienced, independent input to evaluate operational challenges, contractor interfaces, vessel suitability and project risk. Sea Hawk provides consultancy support through professionals whose expertise should be matched to the specific assignment." },
 { t: "h2", x: "Potential Consultancy Areas" }, { t: "ul", x: ["Marine operations review and advisory support.", "Offshore vessel and rig-related operational consultation.", "Project-specific marine risk and execution input.", "Owner or client representation support where agreed.", "Vessel / contractor interface review.", "Operational procedure review.", "Asset or service-provider due-diligence support where appropriate."] },
 { t: "h2", x: "Assignment Model" }, { t: "p", x: "Each consultancy assignment should begin with a clear statement of work defining objectives, deliverables, information relied upon, exclusions and the professional qualifications required. Consultancy output is advisory and does not replace statutory survey, class approval, legal advice or other regulated professional services." },
 { t: "h2", x: "Consultancy Enquiry" }, { t: "p", x: "Describe the project, location, asset type, expected deliverable and required timeline." }, { t: "cta", x: [["/ship-owners/enquiry/", "Discuss a Marine Consultancy Assignment"]] }] },

{ path: "/services/offshore-marine-support/", schema: "Service", title: "Offshore Marine Support Services | Sea Hawk", desc: "Offshore and marine operational support for vessel, rig and project requirements, subject to project scope and verified team expertise.", h1: "Offshore Support Matched to the Project", parent: "/services/", crumb: "Offshore & Marine Support", blocks: [
 { t: "p", x: "Offshore operations require careful coordination between vessel capability, marine personnel, project schedules, contractor interfaces and site-specific risk controls. Sea Hawk can evaluate support requirements for offshore and marine projects where the company has the appropriate personnel and experience." },
 { t: "h2", x: "Support May Include" }, { t: "ul", x: ["Marine coordination and project support.", "Offshore vessel operational liaison.", "Specialist crew / personnel coordination where legally permitted.", "Marine documentation and reporting support.", "Contractor and service-provider coordination.", "Project mobilisation and logistics support within agreed scope."] },
 V("do not name offshore asset classes, oil majors, drilling contractors or project regions unless Sea Hawk can evidence experience."),
 { t: "cta", x: [["/ship-owners/enquiry/", "Discuss an Offshore Requirement"]] }] },

{ path: "/ship-owners/", schema: "Service", title: "Ship Management Solutions for Ship Owners | Sea Hawk", desc: "Integrated commercial, technical, crew and marine support for ship owners and vessel operators. Build a management scope around your operational requirements.", h1: "One Maritime Partner, Clearly Defined Scope", crumb: "Ship Owners", blocks: [
 { t: "p", x: "Ship owners need visibility, accountability and practical execution. Sea Hawk offers modular and integrated support so that the management model can be aligned with vessel type, owner resources and operational priorities." },
 { t: "h2", x: "Typical Owner Requirements" }, { t: "ul", x: ["Need additional shore management capacity.", "Need a crew-management partner for selected ranks or vessels.", "Need technical follow-up and maintenance coordination.", "Need commercial or post-fixture operational support.", "Need specialist marine consultancy for a project or asset.", "Need a combined scope with one primary point of coordination."] },
 { t: "h2", x: "Engagement Process" }, { t: "ol", x: ["Owner shares vessel profile and required scope.", "Sea Hawk performs an initial capability and compliance review.", "Responsibilities, exclusions, reporting and approval limits are defined.", "Commercial proposal and service agreement are finalised.", "Operational handover / mobilisation plan is agreed.", "Performance is reviewed against agreed reporting and service expectations."] },
 { t: "h2", x: "Owner Enquiry" }, { t: "p", x: "Start with the facts. Tell us about the vessel, current arrangement and what you want to improve." }, { t: "cta", x: [["/ship-owners/enquiry/", "Request a Management Discussion"]] }] },

{ path: "/ship-owners/enquiry/", form: "enquiry", title: "Vessel Management Enquiry | Sea Hawk Ship Management", desc: "Submit your vessel management requirement to Sea Hawk for commercial, technical, crew or marine support.", h1: "Vessel Management Enquiry", parent: "/ship-owners/", crumb: "Enquiry", blocks: [] },

{ path: "/seafarers/", title: "Seafarer Hub | Vacancies, Profile & Maritime Guidance | Sea Hawk", desc: "View Sea Hawk seafarer vacancies, register or update your profile, and access practical guidance on STCW, SID, COC and maritime career pathways.", h1: "Your Sea Hawk Seafarer Hub", crumb: "Seafarers", blocks: [
 { t: "p", x: "This section is designed for seafarers who want to view current opportunities, register or update their professional profile and access general guidance on maritime training and documentation." },
 { t: "h2", x: "Important Notice" }, { t: "notice", x: "Information on this website is general guidance only. Official eligibility, training, examination, certification, medical, migration and documentation requirements can change. Always verify the latest requirement with DG Shipping, the relevant maritime administration, approved training institute or other competent authority." },
 { t: "h2", x: "Quick Links" }, { t: "cta", x: [["/seafarers/vacancies/", "Current Vacancies"], ["/seafarers/profile/", "Register / Update Profile"], ["/seafarers/guidance/tme-gme/", "TME/GME Guidance"], ["/seafarers/guidance/gpr/", "GPR Guidance"], ["/seafarers/guidance/stcw/", "STCW Guidance"], ["/seafarers/guidance/sid-card/", "SID Card Guidance"], ["/seafarers/guidance/dns-bsc-nautical-science/", "DNS / B.Sc Nautical Science Guidance"], ["/seafarers/guidance/coc/", "COC Guidance"], ["/recruitment-fraud-advisory/", "Recruitment & Fraud Advisory"]] },
 { t: "h2", x: "Safe Recruitment" }, { t: "p", x: "Use only Sea Hawk’s official website, phone numbers and email domain for recruitment communication. Do not transfer money to personal accounts or individuals claiming to guarantee placement. Report suspicious messages through the official fraud-reporting channel." }] },

{ path: "/seafarers/vacancies/", form: "vacancies", title: "Current Seafarer Vacancies | Sea Hawk Ship Management", desc: "View current maritime and seafarer vacancies published by Sea Hawk. Check rank, vessel type, joining requirements and application status.", h1: "Current Opportunities", parent: "/seafarers/", crumb: "Vacancies", blocks: [
 { t: "p", x: "Vacancies shown on this page are published only through Sea Hawk’s authorised process. Each listing shows an opening date, closing/expiry date and current status." },
 { t: "notice", x: "Sea Hawk does not authorise unofficial agents to guarantee jobs. Verify any recruitment message through our official contact channels before sharing documents or making any payment." }] },

{ path: "/seafarers/profile/", form: "profile", title: "Register Seafarer Profile | Sea Hawk Ship Management", desc: "Register or update your seafarer profile with Sea Hawk for assessment against current and future maritime requirements.", h1: "Register or Update Your Profile", parent: "/seafarers/", crumb: "Profile", blocks: [] },

{ path: "/seafarers/guidance/", title: "Maritime Training & Seafarer Career Guidance | Sea Hawk", desc: "General guidance for seafarers on maritime training, certification pathways and common documents. Always verify current rules with the competent authority.", h1: "Practical Guidance for Seafarers", parent: "/seafarers/", crumb: "Guidance", blocks: [
 { t: "p", x: "Maritime training and certification pathways vary by rank, qualification, sea service and regulatory updates. The Sea Hawk guidance library is intended to help seafarers understand common terms and identify the official source they should check next." },
 { t: "h2", x: "Guidance Principles" }, { t: "ul", x: ["Plain-language explanations.", "A “last reviewed” date on every regulatory article.", "Links to the official DG Shipping / government source where available.", "We summarise and link to original circulars rather than copying them.", "Sea Hawk is not represented as the issuing authority for statutory documents."] },
 { t: "cta", x: [["/seafarers/guidance/tme-gme/", "TME/GME"], ["/seafarers/guidance/gpr/", "GPR"], ["/seafarers/guidance/stcw/", "STCW"], ["/seafarers/guidance/sid-card/", "SID Card"], ["/seafarers/guidance/dns-bsc-nautical-science/", "DNS / B.Sc Nautical Science"], ["/seafarers/guidance/coc/", "COC"]] }] },

guide("tme-gme", "TME / GME Guidance", "TME GME", "Trainee Marine Engineer (TME) and Graduate Marine Engineer (GME) pathways relate to entry and progression within the marine engineering profession. Eligibility and approved-course requirements can change, so candidates should rely on the latest DG Shipping and approved-institute information.", ["Confirm your academic qualification and eligibility.", "Check the current approved training route and institute status.", "Verify medical and documentation requirements.", "Understand course duration, examinations and sea-service pathway.", "Keep copies of official approvals, receipts and certificates."], "Trainee Marine Engineer (TME) and Graduate Marine Engineer (GME) pathways relate to entry and progression within the marine engineering profession."),
guide("gpr", "GPR Guidance", "GPR", "General Purpose Rating (GPR/GP Rating) is a common entry pathway for ratings in the merchant navy. Candidates should verify current age, education, medical, eyesight, approved-institute and course requirements directly from official sources.", ["Verify current eligibility and approved institute.", "Complete required medical/fitness checks through authorised channels.", "Understand course and assessment requirements.", "Confirm CDC/other post-training steps from official guidance.", "Do not pay unofficial agents promising guaranteed placement."], "General Purpose Rating (GPR/GP Rating) is a common entry pathway for ratings in the merchant navy. Candidates should verify current requirements."),
guide("stcw", "STCW Guidance", "STCW", "STCW sets international standards for training, certification and watchkeeping of seafarers. The exact courses required depend on role, vessel, certificate level and current regulatory requirements.", ["Identify which STCW course/certificate applies to your role.", "Use approved training providers.", "Check certificate validity and refresher requirements.", "Maintain digital and physical records.", "Verify any update through DG Shipping or the relevant maritime administration."], "STCW sets international standards for training, certification and watchkeeping of seafarers. The exact courses required depend on role and vessel."),
guide("sid-card", "SID Card Guidance", "SID", "A Seafarer Identity Document (SID) is an official identity document used in the maritime context. Application, biometric, eligibility and issue procedures are controlled by the competent authority and can change over time.", ["Use the official government/DG Shipping portal.", "Ensure personal details match official records.", "Follow current appointment/biometric instructions.", "Track application only through official channels.", "Do not share OTPs or credentials with agents."], "A Seafarer Identity Document (SID) is an official identity document used in the maritime context. Procedures are controlled by the competent authority."),
guide("dns-bsc-nautical-science", "DNS / B.Sc Nautical Science Guidance", "DNS", "Diploma in Nautical Science (DNS) and B.Sc. Nautical Science are recognised education routes associated with deck-officer career pathways. Admission, sponsorship, entrance, medical and training requirements should be checked from current official and institute sources.", ["Compare recognised education pathways.", "Verify institute approval and current intake conditions.", "Understand sponsorship/placement claims before paying fees.", "Check medical and eyesight requirements.", "Review the sea-service and examination pathway after course completion."], "Diploma in Nautical Science (DNS) and B.Sc. Nautical Science are recognised education routes associated with deck-officer career pathways."),
guide("coc", "COC Guidance", "COC", "A Certificate of Competency (COC) confirms professional competence for specified maritime duties and levels. Eligibility, sea service, examinations, revalidation and documentary requirements vary by certificate and administration.", ["Identify the exact COC grade/category.", "Verify required sea service and training.", "Check examination and assessment requirements.", "Follow official application and document-submission process.", "Track revalidation/expiry requirements and regulatory updates."], "A Certificate of Competency (COC) confirms professional competence for specified maritime duties and levels. Requirements vary by certificate."),

{ path: "/about/leadership/", title: "Leadership Team | Sea Hawk Ship Management", desc: "Meet the leadership and maritime professionals behind Sea Hawk Ship Management. View verified experience, responsibilities and areas of expertise.", h1: "Leadership & Management Oversight", parent: "/about/", crumb: "Leadership", blocks: [
 { t: "p", x: "Sea Hawk Ship Management is led by seasoned maritime professionals and master mariners dedicated to operational excellence, client performance, seafarer safety, and statutory compliance. Our executive team brings decades of combined experience across ocean-going vessels and shore-side ship management operations." },
 { t: "h2", x: "Executive Leadership Divisions" },
 { t: "p", x: "Our governance structure is organized into dedicated operational directorates to ensure accountable oversight across every marine vessel under our care:" },
 { t: "ul", x: ["Technical & Fleet Operations Directorate: Responsible for vessel maintenance, dry-docking, class compliance, and technical reliability.", "Crew Management & Human Resources: Directing global seafarer recruitment, STCW compliance, MLC standards, and maritime personnel welfare.", "Commercial Operations & Chartering: Managing post-fixture execution, voyage optimization, marine accounting, and charter party compliance.", "Marine Safety & Quality Assurance (HSEQ): Overseeing safety management systems, environmental compliance, risk audits, and flag-state protocols."] },
 { t: "h2", x: "Leadership Verification Criteria" },
 { t: "p", x: "In compliance with DG Shipping guidance and international maritime governance, Sea Hawk ensures all leadership credentials, master sea-service records, and professional designations are independently audited prior to publication." },
 V("Profiles are published following management verification of: full name, executive designation, verified rank/qualification, sea & shore experience, vessel specializations, responsibilities at Sea Hawk, active memberships, certified headshots, and written confirmation of biography."),
 { t: "h2", x: "Our Management Commitment" },
 { t: "p", x: "Whether managing bulk carriers, tankers, container ships, or offshore support vessels, Sea Hawk leadership operates on principles of complete transparency, zero-incident safety culture, and 24/7 operational availability." },
 { t: "cta", x: [["/contact/", "Speak with Management"], ["/about/", "Explore About Sea Hawk"]] }
] },

{ path: "/about/quality-safety-compliance/", title: "Quality, Safety & Compliance | Sea Hawk Ship Management", desc: "Learn about Sea Hawk Ship Management’s approach to safety, quality, responsible recruitment, compliance and continuous improvement.", h1: "Quality, Safety & Compliance", parent: "/about/", crumb: "Quality, Safety & Compliance", blocks: [
 { t: "h2", x: "Our Commitment" }, { t: "p", x: "Sea Hawk aims to conduct its activities responsibly, with appropriate attention to applicable maritime requirements, contractual obligations, people safety, data protection and ethical business conduct. The exact regulatory framework applicable to a service depends on the activity, vessel, flag, operating area and client arrangement." },
 { t: "h2", x: "Safety" }, { t: "p", x: "Safety is a shared responsibility across ship and shore. Our management approach should support clear roles, competent personnel, timely reporting and appropriate escalation of operational risks. Where Sea Hawk acts within a client’s safety management system, the applicable procedures and responsibilities must be clearly defined." },
 { t: "h2", x: "Quality" }, { t: "p", x: "Quality means delivering the agreed service consistently, documenting responsibilities, maintaining appropriate records and learning from operational feedback. Procedures should be reviewed when regulations, client requirements, risk profiles or operating conditions change." },
 { t: "h2", x: "Responsible Recruitment & Seafarer Welfare" }, { t: "p", x: "Any recruitment or placement activity involving Indian seafarers must be carried out in accordance with applicable Directorate General of Shipping requirements and the scope of the company’s valid authorisation." },
 { t: "h2", x: "Certifications & Registrations" }, { t: "p", x: "Only current, verified credentials are displayed. For every credential: name, issuing authority, number where appropriate, scope, issue date, expiry/validity date and verification link if publicly available." },
 V("No RPSL, ISO, MLC, ISM, CIN, GSTIN or other credential is shown until verified by management. Add each credential with the fields above.") ] },

{ path: "/insights/", form: "list", title: "Maritime Insights & Ship Management Articles | Sea Hawk", desc: "Read practical articles on ship management, crew operations, technical management, safety, seafarer careers and maritime developments.", h1: "Insights", crumb: "Insights", blocks: [
 { t: "p", x: "Practical articles on ship management, crew operations, technical management, safety, seafarer careers and maritime developments." },
 { t: "h2", x: "Content Categories" }, { t: "ul", x: ["Ship Management", "Commercial Operations", "Technical & Maintenance", "Crew Management", "Safety & Compliance", "Offshore & Marine Projects", "Seafarer Careers", "Regulatory Updates"] },
 { t: "h2", x: "Editorial Rules" }, { t: "ul", x: ["Every article answers a real search/user question.", "Each article has an identified author or reviewer with relevant expertise.", "Published and updated dates are shown.", "Regulatory claims cite primary official sources.", "No mass AI publishing without expert review.", "No keyword stuffing or duplicate city/service pages.", "Contextual internal links point to the most relevant service page."] },
 { t: "notice", x: "No articles are published yet. Articles will appear here once reviewed by a qualified author." }] },

{ path: "/news/", form: "list", title: "News & Updates | Sea Hawk Ship Management", desc: "Company announcements, operational updates and selected maritime regulatory updates from Sea Hawk Ship Management.", h1: "News & Updates", crumb: "News", blocks: [
 { t: "p", x: "Follow company announcements, service updates and selected maritime developments relevant to Sea Hawk clients and seafarers. Regulatory updates always link to the original competent-authority publication and include the date reviewed." },
 { t: "notice", x: "No updates have been published yet." }] },

{ path: "/knowledge-centre/", title: "Maritime Knowledge Centre | Sea Hawk", desc: "Explore FAQs, practical guides and downloadable maritime resources from Sea Hawk Ship Management.", h1: "Knowledge Centre", crumb: "Knowledge Centre", blocks: [
 { t: "h2", x: "Planned Resources" }, { t: "ul", x: ["Ship owner enquiry checklist", "Crew requirement checklist", "Seafarer document checklist", "How to verify a recruitment message", "Understanding common maritime certificates", "Preparing documents for a seafarer profile", "Vessel-management transition checklist"] },
 { t: "notice", x: "Downloads will be published as accessible, text-based PDFs with descriptive filenames and update dates. Until then, see the guidance library and the recruitment advisory." },
 { t: "cta", x: [["/seafarers/guidance/", "Guidance library"], ["/recruitment-fraud-advisory/", "Recruitment & Fraud Advisory"]] }] },

{ path: "/recruitment-fraud-advisory/", title: "Recruitment & Fraud Advisory | Sea Hawk Ship Management", desc: "Learn how to verify Sea Hawk recruitment communication, avoid job scams and report suspicious payment or placement requests.", h1: "Recruitment & Fraud Advisory", crumb: "Recruitment & Fraud Advisory", blocks: [
 { t: "p", x: "Protect yourself from fake job offers and unauthorised recruitment messages. Fraudsters may misuse company names, logos, employee identities, messaging apps or fake email addresses to request money or documents." },
 { t: "h2", x: "How to Verify a Sea Hawk Communication" }, { t: "ul", x: ["Check that the email comes from the official seahawkgroup.co.in domain.", "Cross-check the recruiter/contact through the official website phone number.", "Verify the vacancy ID on the official vacancies page where available.", "Confirm any RPSL information against the current DG Shipping record where applicable.", "Do not rely only on a WhatsApp profile photo, forwarded PDF or social-media account."] },
 { t: "h2", x: "Warning Signs" }, { t: "ul", x: ["Guaranteed job or vessel placement without assessment.", "Urgent payment to a personal bank account, wallet or UPI ID.", "Request for OTP, password or remote-access app installation.", "Fake visa, immigration, COC or certificate guarantee.", "Email from a free or misspelled domain pretending to be Sea Hawk.", "Pressure to avoid calling the official office."] },
 { t: "h2", x: "If You Receive a Suspicious Message" }, { t: "ol", x: ["Do not pay or send additional documents.", "Take screenshots and preserve email/message headers where possible.", "Contact Sea Hawk through the official website details.", "Report the account or message through the relevant platform/bank and, where appropriate, law-enforcement/cybercrime channels."] },
 { t: "h2", x: "Official Recruitment Contact" }, { t: "p", x: "Phone: +91 99992 42808 · Landline: 0120-4528060 · Email: info@seahawkgroup.co.in" },
 V("a dedicated verified recruitment email/phone, if management wants one published. Personal recruiter numbers are not published unless management approves.") ] },

{ path: "/privacy-policy/", title: "Privacy Policy | Sea Hawk Ship Management", desc: "Read how Sea Hawk Ship Management collects, uses, protects and manages personal information submitted through its website and related online forms.", h1: "Privacy Policy", crumb: "Privacy Policy", blocks: [
 { t: "p", x: "Last updated: [INSERT DATE]" },
 { t: "p", x: "Sea Hawk Ship Management Private Limited (“Sea Hawk”, “we”, “us” or “our”) respects the privacy of visitors, clients, business contacts and seafarers who use seahawkgroup.co.in and related forms or digital services. This Privacy Policy explains the types of personal information we may collect, why we collect it, how we use it, when it may be shared and the choices available to you." },
 { t: "h2", x: "1. Information We May Collect" }, { t: "ul", x: ["Contact information such as name, email address, telephone number, company and country.", "Business enquiry information including vessel, project and service requirements.", "Seafarer profile information such as rank, qualifications, sea service, availability and professional history.", "Identity, certification and employment-related documents when genuinely required for recruitment, verification or engagement.", "Technical information such as IP address, device/browser information, security logs and basic analytics data.", "Communication records when you contact us through forms, email, phone or authorised messaging channels."] },
 { t: "h2", x: "2. Why We Use Personal Information" }, { t: "ul", x: ["To respond to business enquiries and assess service requirements.", "To manage seafarer registrations, vacancy applications and recruitment-related assessments.", "To verify information, qualifications or documentation where necessary and lawful.", "To communicate about an enquiry, application, engagement or service.", "To maintain website security, prevent fraud and investigate misuse.", "To comply with applicable legal, regulatory, contractual and record-keeping obligations.", "To improve website performance and user experience using proportionate analytics."] },
 { t: "h2", x: "3. Legal Basis / Consent" }, { t: "p", x: "Where consent is required, we will request it in a clear manner and use the information only for the stated purpose. In other cases, processing may be necessary to take steps requested by you, perform a contract, meet legal obligations or protect legitimate operational and security interests, subject to applicable law." },
 { t: "h2", x: "4. Seafarer Data" }, { t: "p", x: "Seafarer information can include sensitive identity and employment-related documents. We aim to collect only information reasonably necessary for the relevant recruitment or management purpose. Submission of a profile does not guarantee employment or placement." },
 { t: "h2", x: "5. Sharing of Information" }, { t: "p", x: "We may share information with authorised employees, service providers, clients/ship owners, travel or operational partners, professional advisers or authorities where this is necessary for the stated purpose, subject to appropriate access controls, confidentiality and applicable law. We do not sell personal data." },
 { t: "h2", x: "6. International Transfers" }, { t: "p", x: "Maritime operations may involve clients, vessels and service providers in multiple countries. Where personal information is transferred outside India, Sea Hawk will apply the safeguards required by applicable law and the relevant contractual arrangement." },
 { t: "h2", x: "7. Retention" }, { t: "p", x: "We retain personal information only for as long as reasonably necessary for the purpose for which it was collected, legitimate business record-keeping, dispute handling, safety/security or legal/regulatory obligations." },
 V("specific retention periods by data category must be defined by management and published or internally documented."),
 { t: "h2", x: "8. Security" }, { t: "p", x: "We use reasonable administrative, technical and organisational measures intended to protect information against unauthorised access, loss, misuse or alteration. No internet or electronic storage method can be guaranteed to be completely secure." },
 { t: "h2", x: "9. Cookies and Analytics" }, { t: "p", x: "The website may use essential cookies and, subject to configuration and applicable consent requirements, analytics or preference cookies. See the Cookie Policy for more information." },
 { t: "h2", x: "10. Your Requests" }, { t: "p", x: "Subject to applicable law, you may contact us to request access, correction, update, deletion, withdrawal of consent or other available rights relating to your personal information. We may need to verify your identity before acting on a request." },
 { t: "h2", x: "11. Children" }, { t: "p", x: "The website is not intended to collect personal data from children except where this is specifically lawful, necessary and appropriately authorised. Candidate forms include age/eligibility controls relevant to maritime recruitment and training." },
 { t: "h2", x: "12. Contact / Grievance" }, { t: "p", x: "Sea Hawk Ship Management Private Limited, Unit No. S-28, Eighth Floor, URBTECH NPX, Sector 153, Noida, Uttar Pradesh 201301, India." },
 V("management must confirm the monitored privacy/grievance email address and responsible role. A generic placeholder email is not published."),
 V("legal/compliance adviser review against actual data flows, vendors and applicable Indian data-protection requirements.") ] },

{ path: "/terms/", title: "Terms of Use | Sea Hawk Ship Management", desc: "Website terms governing use of seahawkgroup.co.in, website content, forms, applications, links and user responsibilities.", h1: "Terms of Use", crumb: "Terms of Use", blocks: [
 { t: "p", x: "Last updated: [INSERT DATE]" },
 { t: "p", x: "By accessing or using seahawkgroup.co.in, you agree to these Terms of Use. If you do not agree, please do not use the website." },
 { t: "h2", x: "1. Website Purpose" }, { t: "p", x: "The website provides information about Sea Hawk’s maritime services, business enquiry options, seafarer opportunities and general educational content. Website information does not by itself create a contract, employment relationship, agency appointment, service commitment or professional guarantee." },
 { t: "h2", x: "2. Accuracy of Information" }, { t: "p", x: "Sea Hawk aims to keep information accurate and current but maritime regulations, vacancies, service availability and requirements may change. Users should verify time-sensitive or regulatory information through the appropriate official source." },
 { t: "h2", x: "3. Seafarer Applications" }, { t: "p", x: "Submitting a profile or applying for a vacancy does not guarantee interview, selection, employment, vessel assignment, salary, visa, documentation or joining. False or misleading information may result in rejection or removal from consideration." },
 { t: "h2", x: "4. Prohibited Use" }, { t: "ul", x: ["Attempting to gain unauthorised access to the website, systems or candidate data.", "Uploading malicious files or code.", "Using automated scraping in a way that disrupts the service or violates applicable law.", "Impersonating Sea Hawk, its staff, a client or another user.", "Submitting false documents or fraudulent applications.", "Using website content to run unauthorised recruitment or payment schemes."] },
 { t: "h2", x: "5. Intellectual Property" }, { t: "p", x: "Unless otherwise stated, website branding, original text, graphics, layouts and other proprietary materials belong to Sea Hawk or are used with permission. You may view and print reasonable extracts for personal or business-reference use, but may not reproduce the website commercially without permission." },
 { t: "h2", x: "6. Third-Party Links" }, { t: "p", x: "Links to DG Shipping, government, training institutes or other websites are provided for convenience. Sea Hawk does not control third-party websites and is not responsible for their availability, security or content." },
 { t: "h2", x: "7. Liability" }, { t: "p", x: "To the extent permitted by law, Sea Hawk is not responsible for losses arising solely from reliance on general website information, third-party content, interruptions or unauthorised fraudulent communications that do not originate from Sea Hawk’s official channels. Nothing in these terms excludes liability that cannot lawfully be excluded." },
 { t: "h2", x: "8. Changes" }, { t: "p", x: "Sea Hawk may update these Terms of Use from time to time. The updated version will be published with a revised “Last updated” date." },
 { t: "h2", x: "9. Governing Law" }, { t: "p", x: "These website terms are intended to be governed by the laws of India, subject to any mandatory law that applies." },
 V("final jurisdiction to be inserted after legal review.") ] },

{ path: "/cookie-policy/", title: "Cookie Policy | Sea Hawk Ship Management", desc: "Learn how Sea Hawk uses essential, preference and analytics cookies on seahawkgroup.co.in and how you can manage cookie choices.", h1: "Cookie Policy", crumb: "Cookie Policy", blocks: [
 { t: "p", x: "Last updated: [INSERT DATE]" },
 { t: "p", x: "Cookies are small text files or similar technologies that websites may store on a device to support essential functions, remember preferences, improve security or measure website usage." },
 { t: "h2", x: "Cookie Categories" }, { t: "ul", x: ["Strictly necessary: required for security, form protection, session handling or core website functionality (for example the staff sign-in session and your saved cookie choice).", "Preferences: remember optional user settings when enabled.", "Analytics: help understand aggregate website usage and performance. Loaded only if you accept.", "Marketing: not used."] },
 { t: "h2", x: "Your Choices" }, { t: "p", x: "Non-essential analytics is off until you accept. “Reject all” is as easy to use as “Accept all”. Your choice is stored and you can reopen the settings from the footer of any page." },
 { t: "h2", x: "Cookie Register" }, V("the final cookie table must be generated from the production build and the actual third-party services in use. Cookie names are not invented.") ] },

{ path: "/disclaimer/", title: "Website Disclaimer | Sea Hawk Ship Management", desc: "Important disclaimer regarding general maritime information, regulatory guidance, vacancies and third-party links on the Sea Hawk website.", h1: "Disclaimer", crumb: "Disclaimer", blocks: [
 { t: "p", x: "Information published on this website is provided for general business and educational purposes. It should not be treated as legal, regulatory, medical, class, statutory survey, immigration, financial or other professional advice unless expressly agreed under a separate professional engagement." },
 { t: "p", x: "Maritime rules, certification pathways, course requirements, vacancies and administrative procedures may change. Users must verify the current requirement with DG Shipping, the applicable maritime administration, flag state, class society, approved institute, employer or other competent authority." },
 { t: "p", x: "Sea Hawk does not guarantee employment, placement, visa approval, certificate issuance, examination outcome, salary, joining date or training admission through information published on this website." },
 { t: "p", x: "External links are provided for convenience and do not imply endorsement. Sea Hawk is not responsible for third-party websites, impersonation, unauthorised agents or fraudulent communications outside its official channels." }] },

{ path: "/accessibility/", title: "Accessibility Statement | Sea Hawk Ship Management", desc: "Sea Hawk aims to make its website accessible and usable for a wide range of people and assistive technologies.", h1: "Accessibility Commitment", crumb: "Accessibility", blocks: [
 { t: "p", x: "Sea Hawk Ship Management aims to provide a website that is usable by people with diverse abilities, devices and assistive technologies. The development target for the website is WCAG 2.2 Level AA. The site has not yet been comprehensively tested, so we say “aims to meet” and make no claim of full conformance." },
 { t: "h2", x: "What We Aim to Support" }, { t: "ul", x: ["Keyboard navigation and visible focus states.", "Semantic headings and landmarks.", "Accessible labels and error messages for forms.", "Text alternatives for meaningful images.", "Sufficient colour contrast.", "Responsive layouts and text zoom.", "Reduced-motion preferences.", "Accessible status and validation messages."] },
 { t: "h2", x: "Feedback" }, { t: "p", x: "If you encounter an accessibility barrier, email info@seahawkgroup.co.in and include the page URL, the issue encountered and the assistive technology/browser used if possible." },
 V("management may replace the feedback address with a dedicated monitored accessibility email.") ] },
];
export const byPath = (p: string) => pages.find((x) => x.path === p);
