export type Field = { name: string; label: string; type: "text" | "email" | "tel" | "select" | "textarea" | "date" | "number" | "file" | "checkbox"; required?: boolean; options?: string[]; hint?: string; max?: number };
export type FormCfg = { kind: "enquiry" | "profile"; fields: Field[] };

export const forms: Record<"enquiry" | "profile", FormCfg> = {
  enquiry: { kind: "enquiry", fields: [
    { name: "company", label: "Company name", type: "text", required: true },
    { name: "contact", label: "Contact person", type: "text", required: true },
    { name: "email", label: "Business email", type: "email", required: true },
    { name: "phone", label: "Phone / WhatsApp", type: "tel", required: true },
    { name: "country", label: "Country", type: "select", options: ["India", "Singapore", "United Arab Emirates", "Greece", "United Kingdom", "United States", "Cyprus", "Germany", "Japan", "Panama", "Liberia", "Marshall Islands", "Other Country"] },
    { name: "vesselName", label: "Vessel name", type: "text" },
    { name: "vesselType", label: "Vessel type", type: "select", required: true, options: ["Bulk Carrier", "Oil / Chemical Tanker", "Gas Carrier (LPG/LNG)", "Container Ship", "General Cargo / Multi-Purpose", "Offshore Vessel (AHTS/PSV)", "Passenger / Cruise Ship", "Tug & Barge", "Other Vessel Type"] },
    { name: "flag", label: "Flag", type: "text" },
    { name: "capacity", label: "DWT / GT / capacity as applicable", type: "text" },
    { name: "yearBuilt", label: "Year built", type: "number" },
    { name: "tradingArea", label: "Current trading area", type: "select", options: ["Worldwide", "Far East / Asia Pacific", "Middle East / Persian Gulf", "Europe / Mediterranean", "US Gulf / Americas", "Coastal India", "West Africa", "Other Area"] },
    { name: "service", label: "Service required", type: "select", options: ["Commercial Management", "Technical Management", "Crewing & Manning", "Marine Consultancy", "Integrated Management"] },
    { name: "vessels", label: "Number of vessels", type: "number" },
    { name: "currentMgmt", label: "Current management arrangement", type: "text" },
    { name: "startDate", label: "Required start date", type: "date" },
    { name: "attachment", label: "Attachment: vessel particulars", type: "file" },
    { name: "requirement", label: "Brief requirement / challenge", type: "textarea", required: true, max: 3000 },
    { name: "consent", label: "I consent to Sea Hawk processing this information as described in the Privacy Policy.", type: "checkbox", required: true },
  ] },
  profile: { kind: "profile", fields: [
    { name: "fullName", label: "Full name as per passport/CDC", type: "text", required: true },
    { name: "mobile", label: "Mobile number", type: "tel", required: true },
    { name: "email", label: "Email", type: "email", required: true },
    { name: "nationality", label: "Nationality", type: "select", required: true, options: ["Indian", "Filipino", "Eastern European", "Other Nationality"] },
    { name: "location", label: "Current city/country", type: "text", required: true },
    { name: "rank", label: "Rank / position applied for", type: "select", required: true, options: ["Master / Captain", "Chief Officer", "2nd Officer", "3rd Officer", "Chief Engineer", "2nd Engineer", "3rd Engineer", "4th Engineer", "Electrical Officer (ETO)", "Deck Cadet", "Engine Cadet", "Bosun", "Able Seaman (AB)", "Ordinary Seaman (OS)", "Pumpman", "Fitter", "Oiler", "Wiper", "Chief Cook", "General Steward", "Other Rank"] },
    { name: "seaService", label: "Total sea service", type: "select", required: true, options: ["Less than 1 Year", "1 - 3 Years", "3 - 5 Years", "5 - 10 Years", "10+ Years"] },
    { name: "rankExperience", label: "Rank experience", type: "text" },
    { name: "vesselExperience", label: "Vessel-type experience", type: "select", options: ["Oil / Chemical Tankers", "Gas Carriers (LPG / LNG)", "Bulk Carriers", "Container Ships", "General Cargo Vessels", "Offshore Support Vessels (AHTS/PSV)", "Tugs & Barges", "Passenger / Ro-Ro", "Multiple Vessel Types"] },
    { name: "cdc", label: "CDC details and expiry", type: "text" },
    { name: "coc", label: "COC / COP details", type: "text" },
    { name: "availability", label: "Availability date", type: "date", required: true },
    { name: "stcw", label: "STCW certificates and validity", type: "textarea" },
    { name: "medical", label: "Medical fitness status and validity", type: "select", options: ["Valid DG Shipping Medical", "Valid International Medical", "Under Process / Renewal", "Not Medically Fit"] },
    { name: "sid", label: "SID status", type: "select", options: ["Valid SID Available", "Applied / Under Process", "Not Applied Yet", "Not Applicable"] },
    { name: "lastVessel", label: "Last vessel / company", type: "text" },
    { name: "expectedSalary", label: "Expected salary", type: "text" },
    { name: "cv", label: "CV upload", type: "file", required: true },
    { name: "consent", label: "I consent to Sea Hawk processing my personal data as described in the Privacy Policy.", type: "checkbox", required: true },
    { name: "accurate", label: "I declare that the information I have submitted is accurate.", type: "checkbox", required: true },
  ] },
};
// Not collected at first touch by design (data minimisation): date of birth, passport details, certificate scans. Request after shortlist.
